Repository knative-extensions/kn-plugin-migration, pull requests merged in 2021-03, with the labels that each got.

#4 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, size/XS

#5 Update CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#9 Add hack scripts
  .gitignore
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  hack/update-deps.sh
  test/presubmit-tests.sh
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/openapiv2/README.md
  vendor/github.com/googleapis/gnostic/openapiv2/document.go
  vendor/github.com/googleapis/gnostic/openapiv2/openapi-2.0.json
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/LICENSE
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/hack/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#7 [Automated] Fix misspellings
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS
